// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resources.Data.Data;

#nullable disable

namespace Resources.Data.Migrations
{
    [DbContext(typeof(MachineDbContext))]
    partial class MachineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Resources.Enteties.Models.Machine", b =>
                {
                    b.Property<Guid>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaseStatus")
                        .HasColumnType("int");

                    b.Property<int>("MachineStatus")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            MachineId = new Guid("83365d55-cc81-4dfe-94e4-0433a74de3a0"),
                            AcquisitionDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            LeaseStatus = 0,
                            MachineStatus = 0,
                            Model = "Model 1",
                            Note = "Maintanence 2024-08-01"
                        },
                        new
                        {
                            MachineId = new Guid("56c7eef9-4144-4ad6-9df3-15fbf6644d04"),
                            AcquisitionDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            LeaseStatus = 1,
                            MachineStatus = 1,
                            Model = "Model 2",
                            Note = "<no notes>"
                        },
                        new
                        {
                            MachineId = new Guid("9b0afc2a-b468-410b-81cd-2aef6bd6ac5f"),
                            AcquisitionDate = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            LeaseStatus = 2,
                            MachineStatus = 0,
                            Model = "Model 3",
                            Note = "Upgraded to BBX7 battery"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
